# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  query_index_product:
    class: AppBundle\Service\QueryIndexProduto
    arguments: [ '@doctrine.orm.entity_manager' ]
