"https://www.{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: true
        headers: ["Accept", "Accept-Language", "Cache-Control", "Set-Cookie"]
        cookies: ["*"]

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"
